config/routes.rb
Rails.application.routes.draw do
  resources :goals

  devise_for :users
  root 'home#index'
  get '/contact_us' => 'home#contact_us'
  get '/jogging' => 'home#jogging'
  

end

app/models/goal.rb
class Goal < ActiveRecord::Base
	belongs_to :user
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
	has_many :goals    
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
   before_action :configure_permitted_parameters, if: :devise_controller?
	protect_from_forgery with: :exception 
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up).push(:name,:last_name,:weight, :height,:sex,:birthdate)
  	devise_parameter_sanitizer.for(:account_update).push(:name,:last_name,:weight, :height,:sex,:birthdate)
  end
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  before_action :set_goal, only: [:show, :edit, :update, :destroy]

  # GET /goals
  # GET /goals.json
  def index
    @goals = Goal.all
  end

  # GET /goals/1
  # GET /goals/1.json
  def show
  end

  # GET /goals/new
  def new
    @goal = Goal.new
  end

  # GET /goals/1/edit
  def edit
  end

  # POST /goals
  # POST /goals.json
  def create
    @goal = Goal.new(goal_params)

    respond_to do |format|
      if @goal.save
        format.html { redirect_to @goal, notice: 'Goal was successfully created.' }
        format.json { render :show, status: :created, location: @goal }
      else
        format.html { render :new }
        format.json { render json: @goal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /goals/1
  # PATCH/PUT /goals/1.json
  def update
    respond_to do |format|
      if @goal.update(goal_params)
        format.html { redirect_to @goal, notice: 'Goal was successfully updated.' }
        format.json { render :show, status: :ok, location: @goal }
      else
        format.html { render :edit }
        format.json { render json: @goal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /goals/1
  # DELETE /goals/1.json
  def destroy
    @goal.destroy
    respond_to do |format|
      format.html { redirect_to goals_url, notice: 'Goal was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_goal
      @goal = Goal.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def goal_params
      params.require(:goal).permit(:user_id, :type_id, :frequency, :goal, :time_started, :time_finished)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
	end
	def contact_us
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/goals/_form.html.erb
<%= form_for(@goal) do |f| %>
  <% if @goal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@goal.errors.count, "error") %> prohibited this goal from being saved:</h2>

      <ul>
      <% @goal.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


<table class="table table-striped">
  <tr>
  <td>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  </td>
  </tr>
  <tr>
  <td>

  <div class="field">
    <%= f.label :type_id %><br>
    <%= f.text_field :type_id %>
  </div>
  </td>
  </tr>
  <tr>
  <td>
  <div class="field">
    <%= f.label :frequency %><br>
    <%= f.number_field :frequency %>
  </div>
  </td>
  </tr>
  <tr>
  <td>
  <div class="field">
    <%= f.label :goal %><br>
    <%= f.number_field :goal %>
  </div>
   </div>
  </td>
  </tr>
 
  <tr>
  <td>
  <div class="field">
    <%= f.label :time_started %><br>
    <%= f.datetime_select :time_started %>
  </div>
   </div>
  </td>
  </tr>
  <tr>
  <td>
  <div class="field">
    <%= f.label :time_finished %><br>
    <%= f.datetime_select :time_finished %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
  </div>
  </td>
  </tr>
  

</table>
<% end %>

app/views/goals/edit.html.erb
<h1>Editing Goal</h1>

<%= render 'form' %>

<%= link_to 'Show', @goal %> |
<%= link_to 'Back', goals_path %>

app/views/goals/index.html.erb
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>index_goals</title>

    <!-- Bootstrap Core CSS -->
    <link href="css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="css/simple-sidebar.css" rel="stylesheet">


 
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
  
 

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    
</head>

<body>

    <div id="wrapper">

        <!-- Sidebar -->
        <div id="sidebar-wrapper">
            <ul class="sidebar-nav">
                <li class="sidebar-brand">
                    <a href="#">
                        Usuario
                    </a>
                </li>
                <li>
                    <a href="#">Band</a>
                </li>
                <li>
                    <a href="#">Alarm</a>
                </li>
                <li>
                    <a href="#">Sessions</a>
                </li>
                <li>
                    <a href="#">Goals</a>
                </li>
                <li>
                    <a href="#">Daily Tracking</a>
                </li>
                <li>
                    <a href="#">Sleeping Tracking</a>
                </li>
                <li>
                    <a href="#">Services</a>
                </li>
                <li>
                    <a href="#">Contact</a>
                </li>
                <li>
                    <%= link_to "Logout", destroy_user_session_path, :method => :delete %>
                </li>
            </ul>
        </div>
        <!-- /#sidebar-wrapper -->

        <!-- Page Content -->
        <div id="page-content-wrapper">
        <a href="#menu-toggle"  id="menu-toggle"><button type="button" class="btn btn-default" aria-label="Left Align">
                           <span class="glyphicon glyphicon-menu-hamburger" aria-hidden="true"></span>
                            </button></a><h1>GOALS</h1>
        <div class="container marketing">

      <!-- Three columns of text below the carousel -->
      <div class="row">
        <div class="col-lg-4">
          <img class="img-circle" src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="Generic placeholder image" width="140" height="140">
          <h2>Calories</h2>
          <p>Donec sed odio dui. Etiam porta sem malesuada magna mollis euismod. Nullam id dolor id nibh ultricies vehicula ut id elit. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Praesent commodo cursus magna.</p>
          <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
        </div><!-- /.col-lg-4 -->
        <div class="col-lg-4">
          <img class="img-circle" src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="Generic placeholder image" width="140" height="140">
          <h2>Steps</h2>
          <p>Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Cras mattis consectetur purus sit amet fermentum. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh.</p>
          <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
        </div><!-- /.col-lg-4 -->
        <div class="col-lg-4">
          <img class="img-circle" src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="Generic placeholder image" width="140" height="140">
          <h2>Weight</h2>
          <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
          <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
        </div><!-- /.col-lg-4 -->
         <div class="col-lg-4">
          <img class="img-circle" src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="Generic placeholder image" width="140" height="140">
          <h2>Distance</h2>
          <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
          <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
        </div><!-- /.col-lg-4 -->
         <div class="col-lg-4">
          <img class="img-circle" src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="Generic placeholder image" width="140" height="140">
          <h2>Heading</h2>
          <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
          <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
        </div><!-- /.col-lg-4 -->
         <div class="col-lg-4">
            <img class="img-circle" src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="Generic placeholder image" width="140" height="140">
            <h2>Heading</h2>
            <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
            <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
        </div><!-- /.col-lg-4 -->
      </div><!-- /.row -->



            <div class="container-fluid">

                <div class="row">
                    <div class="col-lg-12">
                         
                         

                           
                          

                            <table class="table table-striped">
                              <thead>
                                <tr>
                                  <th>User</th>
                                  <th>Type</th>
                                  <th>frequency</th>
                                  <th>goal</th>
                                  <th>Time started</th>
                                  <th>Time finished</th>
                                  <th colspan="3"></th>
                                </tr>
                              </thead>

                              <tbody>
                                <% @goals.each do |goal| %>
                                  <tr>
                                    <td><%= goal.user_id %></td>
                                    <td><%= goal.type_id %></td>
                                    <td><%= goal.frequency %></td>
                                    <td><%= goal.goal %></td>
                                    <td><%= goal.time_started %></td>
                                    <td><%= goal.time_finished %></td>
                                    <td><%= link_to 'Show', goal %></td>
                                    <td><%= link_to 'Edit', edit_goal_path(goal) %></td>
                                    <td><%= link_to 'Destroy', goal, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                                  </tr>
                                <% end %>
                              </tbody>
                            </table>
                        
                    </div>
                </div>
            </div>
        </div>
        <!-- /#page-content-wrapper -->
          <br>

                <div id="wrapper">
                  <button type="button" class="btn btn-default btn-lg">
                  <%= link_to 'New Goal', new_goal_path %>
                    </button>
                    <p class="pull-right"><a href="#">Back to top</a></p>
                </div>
                <!--<%= link_to 'New Goal', new_goal_path %>-->
                
    </div>
    <!-- /#wrapper -->

    <!-- jQuery -->
    <script src="js/jquery.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="js/bootstrap.min.js"></script>

    <!-- Menu Toggle Script -->
    <script>
    $("#menu-toggle").click(function(e) {
        e.preventDefault();
        $("#wrapper").toggleClass("toggled");
    });
    </script>




 

</body>
</html>

app/views/goals/new.html.erb
<h1>New Goal</h1>

<%= render 'form' %>

<%= link_to 'Back', goals_path %>

app/views/goals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @goal.user_id %>
</p>

<p>
  <strong>Type:</strong>
  <%= @goal.type %>
</p>

<p>
  <strong>Burned calories:</strong>
  <%= @goal.burned_calories %>
</p>

<p>
  <strong>Hearth rate:</strong>
  <%= @goal.hearth_rate %>
</p>

<p>
  <strong>Total time:</strong>
  <%= @goal.total_time %>
</p>

<p>
  <strong>Time started:</strong>
  <%= @goal.time_started %>
</p>

<p>
  <strong>Time finished:</strong>
  <%= @goal.time_finished %>
</p>

<%= link_to 'Edit', edit_goal_path(@goal) %> |
<%= link_to 'Back', goals_path %>

app/views/home/contact_us.html.erb
<head>
<title>Contact Us | FiTrack</title>
</head>
<body>
<div class="container">
	<h1 style="border-bottom: 1px solid #A6AAA9; color: #000000;">  Contact Us </h1>
	<table>
  		<col width="60%">
 		<col width="40%">	
		<tr>
			<td>
				<br>
				<p style="text-align: center;"><img src="/assets/contact.jpg" width="820" height="320" /> </p>
				<h4 style="text-align: left;">At <strong>FiTrack</strong>, we love to hear from our clients!</h4>
				<p style="text-align: left;">Feel free to contact us through our contact form, by email, by phone or by regular mail. </p>
				<p style="text-align: left;"><strong>Postal Address: </strong></p>
				
				<p style="text-align: left;">FiTrack</p>
				<p style="text-align: left;">Bolivian Catholic University</p>
				<p style="text-align: left;">Cochabamba, Bolivia </p>
				<p style="text-align: left;"><strong>Telephone: </strong>+591 (6) 539 5750 </p>
				<p style="text-align: left;"><strong>Email:</strong> hello@fitrack.com
				<p style="text-align: left;"><strong>Service hours</strong>: Monday through Friday 10.00-12 &amp; 13.00-18.00 (CET).  Closed on major Bolivian holidays. </p>
			</td>
		</tr>
	</table>
</div>
<br>
</body>

app/views/home/index.html.erb
<head>
  <title>FiTrack</title>

</head>
<body>
<script src="../../assets/js/ie-emulation-modes-warning.js"></script>
    <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
  

  
  <style>
  .carousel-inner > .item > img,
  .carousel-inner > .item > a > img {
      width: 70%;
      margin: auto;
  }
  </style>
	<div id="margincarousel">
 <div id="myCarousel" class="carousel slide" data-ride="carousel">
      <!-- Indicators -->
      <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
      </ol>
      <div class="carousel-inner" role="listbox">
        <div class="item active">
          <img class="first-slide" src="assets/firstimage.jpg" alt="First slide">
          <div class="container">
            <div class="carousel-caption">
              <h1>Fitness Tracker</h1>
              <p>The new way to keep your fitness controlled.</p>
              <p><a class="btn btn-lg btn-primary" href="/users/sign_up" role="button">Start Now</a></p>
            </div>
          </div>
        </div>
        <div class="item">
          <img class="second-slide" src="assets/fitbit.jpg" alt="Second slide">
          <div class="container">
            <div class="carousel-caption">
              <h1>FitBit Charge HR</h1>
              <p>FitBit newest band.</p>
              <p><a class="btn btn-lg btn-primary" href="https://www.fitbit.com/chargehr" role="button">Learn More</a></p>
            </div>
          </div>
        </div>
        <div class="item">
          <img class="third-slide" src="assets/microsoft.jpg" alt="Third slide">
          <div class="container">
            <div class="carousel-caption">
              <h1>Microsoft Band</h1>
              <p>Look what Microsoft got for you.</p>
              <p><a class="btn btn-lg btn-primary" href="https://www.microsoft.com/Microsoft-Band/en-us" role="button">Learn More</a></p>
            </div>
          </div>
        </div>
      </div>
      <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div><!-- /.carousel -->
</div>


 
	
</body>

app/views/home/jogging.html.erb
<head>
  <title>Jogging | FiTrack</title>
  <script language="javascript"> 
var base = 60;
var clocktimer,dateObj,dh,dm,ds,ms;
var readout='';
var h=1;
var m=1;
var tm=1;
var s=0;
var ts=0;
var ms=0;
var show=true;
var init=0;
var mPLUS=new Array(
'm0',
'm1',
'm2',
'm3',
'm4',
'm5',
'm6',
'm7',
'm8',
'm9');
var ii=0;

function clearALL() {
clearTimeout(clocktimer);
h=1;m=1;tm=1;s=0;ts=0;ms=0;
init=0;show=true;
readout='00:00:00.00';
document.clockform.clock.value=readout;
var CF = document.clockform;
for (ij=0;ij<=9;ij++) { CF[mPLUS[ij]].value = ''; }
ii = 0;}

function addMEM() {
if (init>0) {var CF = document.clockform;
CF[mPLUS[ii]].value = readout;
if (ii==9) { ii = 0; } else { ii++; }}}


function startTIME() { 
var cdateObj = new Date();
var t = (cdateObj.getTime() - dateObj.getTime())-(s*1000);

if (t>999) { s++; }

if (s>=(m*base)) {ts=0;
m++;} else {ts=parseInt((ms/100)+s);
if(ts>=base) { ts=ts-((m-1)*base); }}

if (m>(h*base)) {tm=1;
h++;} else {tm=parseInt((ms/100)+m);
if(tm>=base) { tm=tm-((h-1)*base); }}

ms = Math.round(t/10);
if (ms>99) {ms=0;}
if (ms==0) {ms='00';}
if (ms>0&&ms<=9) { ms = '0'+ms; }

if (ts>0) { ds = ts; if (ts<10) { ds = '0'+ts; }} else { ds = '00'; }
dm=tm-1;
if (dm>0) { if (dm<10) { dm = '0'+dm; }} else { dm = '00'; }
dh=h-1;
if (dh>0) { if (dh<10) { dh = '0'+dh; }} else { dh = '00'; }

readout = dh + ':' + dm + ':' + ds + '.' + ms;
if (show==true) { document.clockform.clock.value = readout; }

clocktimer = setTimeout("startTIME()",1);}

function findTIME() {
if (init==0) {dateObj = new Date();
startTIME();
init=1;} else {if(show==true) {show=false;} else {show=true;}}}
</script>

</head>
<body>
<div class="container">
<h1 style="border-bottom: 1px solid #A6AAA9; color: #000000;">  Jogging  </h1>
<img src="/assets/jogging.jpg" style= "position: absolute; right:400px; width="50" height="50"">
</div>

<div class="container">
  <div style="width:500px;height:200px;border:1px solid #000;">The map</div>
  <br>
</div>

<div class="container">
<table  WIDTH="50%">
  <tr>
   <td style="font-size: 100%;"> Calories Burned: </td>
   <td style="font-size: 100%;"> Time: </td>
   <td style="font-size: 100%;"> Day: </td>
  </tr>
    <tr>
    <td> 000 </td>
    <td > 00:00 </td>
    <td > Monday </td>
  </tr>
</table> 

<form name="clockform">

<input name="starter" onclick="findTIME()" style="font-weight: bold; width: 200px;" type="button" value="Start Jogging/Stop" />
<input name="clearer" onclick="clearALL()" type="button" value="Reset" />
<input name="clock" style="font-size: 24; font-weight: bold; height: 35px; text-align: center; width: 174px;" value="00:00:00.00" />
</form>

<form>

</form>

</div>




	
</body>

 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  
  <%= csrf_meta_tags %>
  <link rel="stylesheet" type="text/css" href="blogstyle.scss">
   <script src="../../assets/js/ie-emulation-modes-warning.js"></script>
   <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
</head>

<header>
	    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">FiTrack</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav navbar-left">
                  
	                <li><a href="/">Fitness Tracker</a>
	                </li>
	                
	                <li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" href="/">
     					 Bands <span class="caret"></span>
    				</a>
	                	<ul class="dropdown-menu">
                    		<li><a href="https://www.microsoft.com/Microsoft-Band/en-us">Microsoft Band</a></li>
		                    <li><a href="https://www.fitbit.com/chargehr">FitBit Charge HR</a></li>
		                 </ul>
	                </li>
	                <li class="dropdown">
	                		<a class="dropdown-toggle" data-toggle="dropdown" href="/" >
    					  	Disciplines <span class="caret"></span>
  					  		</a>
	                	<ul class="dropdown-menu">
		                    	<li><a href="/jogging">Jogging</a></li>
		                    	<li><a href="/">Cycling</a></li>
		                    	<li><a href="/">Weight Lifting</a></li>
		                </ul>
	                </li>
	                 <li class="dropdown">
              
            
            </li>
	            </ul>
              <ul class="nav navbar-nav navbar-right">
                  <li><a href="/users/sign_in">Sign In</a>
                  </li>
                  <form action="/users/sign_up" class="navbar-form navbar-left" role="signup">
                    <button class="btn btn-default" >Sign Up</button>
                  </form>
                  </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>


    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
    <script src="../../dist/js/bootstrap.min.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="../../assets/js/ie10-viewport-bug-workaround.js"></script>
</header>
<body>

<%= yield %>

</body>
<footer class="modal-footer" style="position: fixed; bottom: 0px; padding-top:10px; background:#ffffff">
        <p class="text-muted">Copyright © 2015 FiTrack. All rights reserved. | <a style="color: #000000;" href="/">Terms of Use</a> | <a style="color: #000000;" href="/">Updated Privacy Policy</a> | <a style="color: #000000;"  href="/contact_us">Contact Us</a> | EN (US)</p>
      
    </footer>
</html>